# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tick_message_v3.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tick_message_v3.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15tick_message_v3.proto\x12\x0cib_stream.v3\"\xbd\x02\n\x0bTickMessage\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\n\n\x02st\x18\x02 \x01(\x03\x12\x0b\n\x03\x63id\x18\x03 \x01(\x05\x12\n\n\x02tt\x18\x04 \x01(\t\x12\x0b\n\x03rid\x18\x05 \x01(\x05\x12\x0e\n\x01p\x18\n \x01(\x01H\x00\x88\x01\x01\x12\x0e\n\x01s\x18\x0b \x01(\x01H\x01\x88\x01\x01\x12\x0f\n\x02\x62p\x18\x0c \x01(\x01H\x02\x88\x01\x01\x12\x0f\n\x02\x62s\x18\r \x01(\x01H\x03\x88\x01\x01\x12\x0f\n\x02\x61p\x18\x0e \x01(\x01H\x04\x88\x01\x01\x12\x0f\n\x02\x61s\x18\x0f \x01(\x01H\x05\x88\x01\x01\x12\x0f\n\x02mp\x18\x10 \x01(\x01H\x06\x88\x01\x01\x12\x10\n\x03\x62pl\x18\x14 \x01(\x08H\x07\x88\x01\x01\x12\x10\n\x03\x61ph\x18\x15 \x01(\x08H\x08\x88\x01\x01\x12\x10\n\x03upt\x18\x16 \x01(\x08H\t\x88\x01\x01\x42\x04\n\x02_pB\x04\n\x02_sB\x05\n\x03_bpB\x05\n\x03_bsB\x05\n\x03_apB\x05\n\x03_asB\x05\n\x03_mpB\x06\n\x04_bplB\x06\n\x04_aphB\x06\n\x04_uptb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tick_message_v3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKMESSAGE']._serialized_start=40
  _globals['_TICKMESSAGE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
